config/routes.rb
Stagely::Application.routes.draw do
  resources :artists

  resources :genres
  resources :subgenres

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :venues
  resources :events do
    member do
      get :attend
      get :consider
    end
  end

  match '/search',  to: 'events#search'
  match '/:id' => "shortener/shortened_urls#show"

  match "/auth/:facebook/callback" => "sessions#create"
  match "/auth/failure" => "events#index"

  root :to => 'events#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	attr_accessible :name
	has_many :events
	has_many :subgenres
end

app/controllers/genres_controller.rb
class GenresController < InheritedResources::Base
	before_filter :power_user, only: [:new, :create, :edit, :update, :destroy]
end

app/views/genres/_form.html.erb
<%= form_for @genre, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Genre</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', genres_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/genres/edit.html.erb
<div class="span8">
<%= render :partial => 'form' %>
</div>

app/views/genres/index.html.erb
<% provide :title, "Music genres in New York City" %>

<div class="span8">
<div id ="event_details">
<h3>Genres</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>

     

    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.name, genre_path(genre) %></td>
        <td>
        <% if current_user && current_user.uid == "568790501" %>
          <%= link_to 'Edit', edit_genre_path(genre), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', genre_path(genre), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user && current_user.uid == "568790501" %>
<%= link_to 'New', new_genre_path, :class => 'btn btn-primary' %>
<%end%>
</div>

app/views/genres/new.html.erb
<div class="span8">
<%= render :partial => 'form' %>
</div>

app/views/genres/show.html.erb
<% provide :title, @genre.name + " in New York City"%>

<div class="span8">
<div id ="event_details">
<h3><%= @genre.name %></h3>
</div>
<% if current_user && current_user.uid == "568790501" %>
<div class="form-actions">
  <%= link_to 'Back', genres_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_genre_path(@genre), :class => 'btn' %>
  <%= link_to 'Delete', genre_path(@genre), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>
<%end%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Subgenres</th>
      


    </tr>
  </thead>
<tbody>
    <% @genre.subgenres.each do |subgenre| %>
      <tr>
        
        <td><%= link_to subgenre.name, subgenre_path(subgenre) %></td>
        
        <td>
        <% if current_user && current_user.uid == "568790501" %>
          <%= link_to 'Edit', edit_subgenre_path(subgenre), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', subgenre_path(subgenre), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% if current_user && current_user.uid == "568790501" %>
<%= link_to 'New subgenre', new_subgenre_path, :class => 'btn btn-primary' %>
</div>
<%end%>
 
 