config/routes.rb
Stagely::Application.routes.draw do
  resources :artists

  resources :genres
  resources :subgenres

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :venues
  resources :events do
    member do
      get :attend
      get :consider
    end
  end

  match '/search',  to: 'events#search'
  match '/:id' => "shortener/shortened_urls#show"

  match "/auth/:facebook/callback" => "sessions#create"
  match "/auth/failure" => "events#index"

  root :to => 'events#index'

end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
        attr_accessible :venue_id, :date, :time, :price, :who, :topic_id, :type_id, :artist_id
	validates_presence_of :artist_id, :venue_id, :time, :date
	validates_length_of :description, :maximum => 44
        validates_length_of :who, :maximum => 44
	
        belongs_to :artist
	belongs_to :venue
        belongs_to :user


	#before_save :generate_keywords
        before_save :make_date_precise
        #before_save :remove_stagely_as_author

	define_index do
	    # fields
	    #indexes description, :sortable => true
            indexes artist(:name), :as => :artist
            indexes artist.subgenre.name, :as => :subgenre
            indexes artist.subgenre.genre.name, :as => :genre
            #indexes artist(:subgenre), :as => :subgenre
            #indexes genre(:name), :as => :genre
            indexes venue(:name), :as => :venue
            indexes venue.street, :as => :street
            indexes venue.town, :as => :town

	    # attributes
            has date, venue_id, artist_id
	  
  	end

        def to_param
                self.who = "" if self.who == nil
                "#{id}-#{self.who}"
        end

  	private

        def make_date_precise
                date = (self.date.year.to_s + "-" + self.date.month.to_s + "-" + self.date.day.to_s + " " + self.time.to_s(:time))
                self.date = Time.zone.parse(date)
                #self.time = self.date
                
        end

  	def generate_keywords
            text= self.who + ' ' + self.description

            text = text.gsub(/\W/, ' ')

            array = text.split(/\s+/)

            array = array.collect {|e| e.downcase if e != nil}

            position = array.inject(Hash.new(0)) {|h,x| h[x]+=1;h}
            position.delete_if {|key, value| key == nil}
            position.delete_if {|key, value| key.length < 4}


            keywords = (position.keys).join(' ')
                         
            keywords = ' ' + keywords + ' '

              if keywords != nil
                        
                #keywords=keywords.sub('—',' ')
                keywords=keywords.sub(' ','')
                keywords=keywords.sub(' jan ',' ')
                keywords=keywords.sub(' feb ',' ')
                keywords=keywords.sub(' mar ',' ')
                keywords=keywords.sub(' apr ',' ')
                keywords=keywords.sub(' may ',' ')
                keywords=keywords.sub(' jun ',' ')
                keywords=keywords.sub(' jul ',' ')
                keywords=keywords.sub(' aug ',' ')
                keywords=keywords.sub(' sep ',' ')
                keywords=keywords.sub(' oct ',' ')
                keywords=keywords.sub(' nov ',' ')
                keywords=keywords.sub(' dec ',' ')
                
                keywords=keywords.sub(' monday ',' ')
                keywords=keywords.sub(' tuesday ',' ')
                keywords=keywords.sub(' wednesday ',' ')
                keywords=keywords.sub(' thursday ',' ')
                keywords=keywords.sub(' friday ',' ')
                keywords=keywords.sub(' saturday ',' ')
                keywords=keywords.sub(' sunday ',' ')
                   
                keywords=keywords.sub(' a ',' ')
                keywords=keywords.sub(' ap ',' ')
                keywords=keywords.sub(' about ',' ')
                keywords=keywords.sub(' an ',' ')
                keywords=keywords.sub(' am ',' ')
                keywords=keywords.sub(' and ',' ')
                keywords=keywords.sub(' are ',' ')
                keywords=keywords.sub(' at ',' ')
                keywords=keywords.sub(' as ',' ')
                keywords=keywords.sub(' be ',' ')
                keywords=keywords.sub(' but ',' ')
                keywords=keywords.sub(' by ',' ')
                keywords=keywords.sub(' can ',' ')
                keywords=keywords.sub(' do ',' ')
                keywords=keywords.sub(' does ',' ')
                keywords=keywords.sub(' for ',' ')
                keywords=keywords.sub(' from ',' ')
                keywords=keywords.sub(' got ',' ')
                keywords=keywords.sub(' has ',' ')
                keywords=keywords.sub(' have ',' ')
                keywords=keywords.sub(' he ',' ')
                keywords=keywords.sub(' her ',' ')
                keywords=keywords.sub(' him ',' ')
                keywords=keywords.sub(' if ',' ')
                keywords=keywords.sub(' ii ',' ')
                keywords=keywords.sub(' in ',' ')
                keywords=keywords.sub(' into ',' ')
                keywords=keywords.sub(' is ',' ')
                keywords=keywords.sub(' it ',' ')
                keywords=keywords.sub(' no ',' ')
                keywords=keywords.sub(' not ',' ')
                keywords=keywords.sub(' now ',' ')
                keywords=keywords.sub(' of ',' ')
                keywords=keywords.sub(' off ',' ')
                keywords=keywords.sub(' on ',' ')
                keywords=keywords.sub(' out ',' ')
                keywords=keywords.sub(' over ',' ')
                keywords=keywords.sub(' she ',' ')
                keywords=keywords.sub(' should ',' ')
                keywords=keywords.sub(' so ',' ')
                keywords=keywords.sub(' some ',' ')
                keywords=keywords.sub(' that ',' ')
                keywords=keywords.sub(' the ',' ')
                keywords=keywords.sub(' their ',' ')
                keywords=keywords.sub(' them ',' ')
                keywords=keywords.sub(' there ',' ')
                keywords=keywords.sub(' they ',' ')
                keywords=keywords.sub(' this ',' ')
                keywords=keywords.sub(' to ',' ')
                keywords=keywords.sub(' under ',' ')
                keywords=keywords.sub(' up ',' ')
                keywords=keywords.sub(' you ',' ')
                keywords=keywords.sub(' was ',' ')
                keywords=keywords.sub(' we ',' ')
                keywords=keywords.sub(' what ',' ')
                keywords=keywords.sub(' when ',' ')
                keywords=keywords.sub(' which ',' ')
                keywords=keywords.sub(' who ',' ')
                keywords=keywords.sub(' will ',' ')
                keywords=keywords.sub(' with ',' ')

                
                keywords=keywords.sub(' der ',' ')
                keywords=keywords.sub(' die ',' ')
                keywords=keywords.sub(' das ',' ')
                keywords=keywords.sub(' ein ',' ')
                keywords=keywords.sub(' eine ',' ')
                keywords=keywords.sub(' einer ',' ')
                keywords=keywords.sub(' sein ',' ')
                keywords=keywords.sub(' seine ',' ')
                keywords=keywords.sub(' ihr ',' ')
                keywords=keywords.sub(' ihre ',' ')
                keywords=keywords.sub(' auf ',' ')
                keywords=keywords.sub(' von ',' ')
                
                keywords=keywords.sub(' vom ',' ')
                keywords=keywords.sub(' zu ',' ')
                keywords=keywords.sub(' wegen ',' ')
                keywords=keywords.sub(' montag ',' ')
                keywords=keywords.sub(' dienstag ',' ')
                keywords=keywords.sub(' mittwoch ',' ')
                keywords=keywords.sub(' donnerstag ',' ')
                   
                keywords=keywords.sub(' freitag ',' ')
                keywords=keywords.sub(' samstag ',' ')
                keywords=keywords.sub(' sonntag ',' ')
                keywords=keywords.sub(' hat ',' ')
                keywords=keywords.sub(' haben ',' ')
                keywords=keywords.sub(' hatte ',' ')
                keywords=keywords.sub(' hatten ',' ')
                keywords=keywords.sub(' wie ',' ')
                keywords=keywords.sub(' wo ',' ')
                keywords=keywords.sub(' wann ',' ')
                keywords=keywords.sub(' wer ',' ')
                keywords=keywords.sub(' wen ',' ')
                keywords=keywords.sub(' wenn ',' ')
                keywords=keywords.sub(' den ',' ')
                keywords=keywords.sub(' dieses ',' ')
                keywords=keywords.sub(' heute ',' ')
                keywords=keywords.sub(' nicht ',' ')
                keywords=keywords.sub(' noch ',' ')
                keywords=keywords.sub(' als ',' ')
                keywords=keywords.sub(' zum ',' ')
                keywords=keywords.sub(' nach ',' ')
                keywords=keywords.sub(' vor ',' ')
                keywords=keywords.sub(' sie ',' ')
                keywords=keywords.sub(' sei ',' ')
                keywords=keywords.sub(' so ',' ')
                keywords=keywords.sub(' werde ',' ')
                keywords=keywords.sub(' ist ',' ')
                keywords=keywords.sub(' in ',' ')
                keywords=keywords.sub(' es ',' ')
                keywords=keywords.sub(' sich ',' ')
                keywords=keywords.sub(' ob ',' ')
                keywords=keywords.sub(' sind ',' ')
                keywords=keywords.sub(' solche ',' ')
                keywords=keywords.sub(' wurde ',' ')
                keywords=keywords.sub(' dass ',' ')
                keywords=keywords.sub(' am ',' ')
                keywords=keywords.sub(' und ',' ')
                keywords=keywords.sub(' oder ',' ')
                keywords=keywords.sub(' an ',' ')
                keywords=keywords.sub(' einige ',' ')
                keywords=keywords.sub(' dann ',' ')
                keywords=keywords.sub(' wird ',' ')
                keywords=keywords.sub(' werden ',' ')
                keywords=keywords.sub(' gab ',' ')
                keywords=keywords.sub(' denn ',' ')
                keywords=keywords.sub(' da ',' ')
                keywords=keywords.sub(' des ',' ')
                keywords=keywords.sub(' bei ',' ')
                keywords=keywords.sub(' durch ',' ')
                keywords=keywords.sub(' unter ',' ')
                keywords=keywords.sub(' etwas ',' ')

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :new, :create, :destroy, :attend, :consider]
  before_filter :correct_user, only: [:edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index

    
    if params[:time] == "week"
      @events = Event.search :match_mode => :fullscan, :with => {:date => 1.hour.ago..7.days.from_now} 
    elsif params[:time] == "tomorrow"
      @events = Event.search :match_mode => :fullscan, :with => {:date => Time.zone.parse(Date.tomorrow.to_s(:db))..Time.zone.parse(Date.tomorrow.tomorrow.to_s(:db))}
    elsif params[:time] == "month"
      @events = Event.search :match_mode => :fullscan, :with => {:date => 1.hour.ago..30.days.from_now}
    else
      @events = Event.search :match_mode => :fullscan, :with => {:date => 1.hour.ago..Time.zone.parse(Date.tomorrow.to_s(:db))}
    end


    find_topics(@events)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def search
    if params[:time] == "week"
      @events = Event.search params[:q], :match_mode => :any, :with => {:date => 1.hour.ago..7.days.from_now} 
    elsif params[:time] == "tomorrow"
      @events = Event.search params[:q], :match_mode => :any, :with => {:date => Time.zone.parse(Date.tomorrow.to_s(:db))..Time.zone.parse(Date.tomorrow.tomorrow.to_s(:db))}
    elsif params[:time] == "today"
      @events = Event.search params[:q], :match_mode => :any, :with => {:date => 1.hour.ago..Time.zone.parse(Date.tomorrow.to_s(:db))}
      
    else
      @events = Event.search params[:q], :match_mode => :any, :with => {:date => 1.hour.ago..30.days.from_now}
    end
    find_topics(@events)
    @search_breadcrumb = params[:q]
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    @related_events = Event.search @event.artist.subgenre.name, :match_mode => :any, :with => {:date => 1.hour.ago..30.days.from_now}, :limit => 9
    @related_events.delete(@event)
    #@time_breadcrumb = 
    #@town_breadcrumb = @event.venue.town
    @time_breadcrumb = event_time
    @genre_breadcrumb = @event.artist.subgenre.genre.name
    @subgenre_breadcrumb = @event.artist.subgenre.name

    #Shortener::ShortenedUrl.generate(request.url)
    #@keywords = @event.keywords.split(/\s+/)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @action_breadcrumb = "Post a concert"
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @action_breadcrumb = "Edit event"
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end


  def event_time
     if @event.date > 1.hour.ago && @event.date < Time.zone.parse(Date.tomorrow.to_s(:db))
      return "Today"
    elsif @event.date > Time.zone.parse(Date.today.to_s(:db)) && @event.date < Time.zone.parse(Date.tomorrow.tomorrow.to_s(:db))
      return "Tomorrow"
    elsif @event.date > Time.zone.parse(Date.tomorrow.to_s(:db)) && @event.date < 7.days.from_now
      return "This week"
    elsif @event.date > 7.days.from_now && @event.date < 30.days.from_now
      return "This month"
    end
  end

  def filter_time
    if params[:time] == "today"
      return "Today"
    elsif params[:time] == "tomorrow"
      return "Tomorrow"
    elsif params[:time] == "week"
      return "This week"
    elsif params[:time] == "month"
      return "This month"
    end
  end

  def correct_user
    @event =Event.find(params[:id])
    redirect_to root_url if current_user != @event.user
  end

  def attend
        event_id = params[:event_id]
        event = Event.find(event_id)
        event_url = params[:event_url]
        type = params[:type]
        
        auth = session[:auth]
        token = auth["credentials"]["token"]
        me = FbGraph::User.me(token)
        if type == "attend"
          me.feed!(
            :message => 'will attend "' + event.artist.name + ' @ ' + event.venue.name + ', ' + event.venue.town + '" ' + event_url

          )
        else
          me.feed!(
            :message => 'considers attending "' + event.artist.name + ' @ ' + event.venue.name + '" ' + event_url
          )
        end

        redirect_to (event || root_url)
  end

  




end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper

	def add_new_venue
		return link_to 'add new venue', new_venue_path
	end

	def add_new_artist
		return link_to 'add new artist/band', new_artist_path
	end

	def submit_price
		return link_to_function "enter price", "$('#price_input, .icon').toggle('price_input')"
	end

	def shoort_url(url)
	    short_url = Shortener::ShortenedUrl.generate(url)
	    short_url ? url_for(:controller => :"shortener/shortened_urls", :action => :show, :id => short_url.unique_key, :only_path => false) : url
	end

	def tweet_text(event)
		"#{event.artist.name} @ #{event.venue.name}, #{event.venue.town}, #{event.date.strftime("%b%d")}, #{event.time.strftime("%I:%M%p")},"
	end

	def author(event)
			return link_to event.user.name, "https://www.facebook.com/#{event.user.uid}"
	end

	def who_character_count
		render :partial => 'who_counter'
	end

	def description_character_count
		render :partial => 'description_counter'
	end


end

app/views/events/_description_counter.html.erb
<div>Characters left: <span id="description-char-count">44</span></div>

app/views/events/_event.html.erb
<tr>
        <td><%= link_to (event.artist.name + " @ " + event.venue.name), event_path(event) %> - <%= event.time.strftime("%I:%M %p") %>, <%= event.date.strftime("%a, %b %d") %> - <%= event.venue.town %> </td>
</tr>

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <%= f.association :artist, hint: add_new_artist, :prompt => "select artist/band" %>  
    <%= f.association :venue, hint: add_new_venue, :prompt => "select venue" %>
    <%= f.input :date, :as => :string %>
    <%= f.input :time, :prompt => {:minute => 'Minute', :hour => 'Hour'}, :minute_step => 15, label: "Start time" %>    
    <%= f.input :price, :input_html => { :maxlength => 15 }%>
    <div class="form-actions">
      <%= f.submit 'Post concert', :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', events_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/events/_who_counter.html.erb
<div>Characters left: <span id="who-char-count">44</span></div>

app/views/events/depot.html.erb
	<div class="related_links">
	Suggestions:
		<% @keywords.each do |keyword| %>
		<%= link_to keyword, :action => "search", :q => keyword %> 
		<%end%>
	</div>
	<br>

	        <div id="post_event_button">
            <%= link_to 'add an event', new_event_path, :class => 'btn btn-primary' %>
        </div>


        


      
      


        <%if params[:action] == "index"%>
          <div id="slogan">
            Classical music in Berlin 
          </div>  
        <%end%>

            <ul style="list-style-type:none">
                  <li style="display:inline">
                  <a href="#">Home</a> >
                  </li>
                  <li style="display:inline">
                  <a href="#">Today</a> >
                  <li style="display:inline">
                  <a href="#">Mitte</a> >
                  </ul>



 <div class="span8">
                  <ul class="breadcrumb" style="list-style-type:none">
                  <li>
                  <a href="/">Home</a> >
                  </li>

                  <li>
                  <% if @time_breadcrumb %>
                  <%= link_to @time_breadcrumb, :controller => "events", :action => "index", :time => get_breadcrumb_time(@time_breadcrumb) %> >
                  </li>
                  <%end%>
                  <% if @town_breadcrumb %>
                  <li>
                  <%= link_to @town_breadcrumb, :controller => "events", :action => "search", :q => @town_breadcrumb, :time => get_breadcrumb_time(@time_breadcrumb) %>
                  </li>
                  <%end%>
                  <% if @search_breadcrumb %>
                  <li>
                  <%= link_to @search_breadcrumb, :controller => "events", :action => "search", :q => @search_breadcrumb %>
                  </li>
                  <%end%>
                  </ul>
                  


          </div>



            <div class="related_links">
      Suggestions:
            <% @keywords.each do |keyword| %>
             <%= link_to keyword, :action => "search", :q => keyword %>
             <% if keyword != @keywords.last %>
              ·
              <% end %>
            <%end%> 
      </div>

                          <li>
                    <% if @time_breadcrumb %>
                     > <%= link_to @time_breadcrumb, :controller => "events", :action => "index", :time => get_breadcrumb_time(@time_breadcrumb) %>
                    </li>
                    <%end%>
                    <% if @town_breadcrumb %>
                    <li>
                    > <%= link_to @town_breadcrumb, :controller => "events", :action => "search", :q => @town_breadcrumb, :time => get_breadcrumb_time(@time_breadcrumb) %>
                    </li>
                    <%end%>


                                        <li>
                    <% if @time_breadcrumb %>
                     > <%= link_to @time_breadcrumb, :controller => "events", :action => "index", :time => get_breadcrumb_time(@time_breadcrumb) %>
                    </li>
                    <%end%>

<script type="text/javascript"> var maxLen = 44; $(function() {   setCharCount($('#event_who')); }); $('#event_who').live('keyup keydown', function(e) { setCharCount($(this));  });  function setCharCount(object) {   var left = maxLen - object.val().length;  $('#who-char-count').html(left); }</script>

<script type="text/javascript"> var maxLen = 44; $(function() {   setCharCount2($('#event_description')); }); $('#event_description').live('keyup keydown', function(e) { setCharCount2($(this));  });  function setCharCount2(object) {   var left = maxLen - object.val().length;  $('#description-char-count').html(left); }</script>

app/views/events/edit.html.erb
<div class="span12">
<%= render :partial => 'form' %>
</div>

app/views/events/index.html.erb
<% provide :title, "Concerts in New York City" %>
<div class="span8" style="margin-top:-59px">
	<ul class="nav nav-tabs">
	     <% if params[:time] == nil %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    	<a href="events_path">Today</a>
	    </li>
	     <% if params[:time] == "tomorrow" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <a href="/?time=tomorrow">Tomorrow</a></li>
	     <% if params[:time] == "week" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <a href="/?time=week">This week</a></li>
	     <% if params[:time] == "month" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <a href="/?time=month">This month</a></li>
	</ul>
	<table class="table table-striped">
	  <tbody>
	<%= render @events %>
	  </tbody>
	</table>

</div>

<div class="span4">
		<div class="topic_navigation">
		Genres:
		
		<br><br>
		<table class="table table-striped">
	  <tbody>
			<% @words.each do |keyword| %>
			<%= link_to keyword[0] + " (" + keyword[1].to_s + ")", :action => "search", :q => keyword[0], :time => params[:time] %> <br><br>
			<%end%>
	  </tbody>

	</table>
	</div>
</div>

app/views/events/new.html.erb
<div class="span12">
<%= render :partial => 'form' %>
</div>

app/views/events/search.html.erb
<% provide :title, params[:q] + " in New York City" %>
<div class="span8">
	<div id ="event_details">

		<h3><%= params[:q] + " in New York City" %></h3>
	</div>

	<ul class="nav nav-tabs">
	     <% if params[:time] == "today" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	     <%= link_to "Today", :action => "search", :q => params[:q], :time => "today" %> 	
	    </li>
	     <% if params[:time] == "tomorrow" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <%= link_to "Tomorrow", :action => "search", :q => params[:q], :time => "tomorrow" %></li>
	     <% if params[:time] == "week" %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <%= link_to "This week", :action => "search", :q => params[:q], :time => "week" %></li>
	     <% if params[:time] == nil %> 
	     <li class="active"> 
	     <%else%>
	     <li>
	     <%end%>
	    <%= link_to "This month", :action => "search", :q => params[:q] %></li>
	</ul>

<table class="table table-striped">
  <thead>
  </thead>
  <tbody>
<%= render @events %>
  </tbody>
</table>

</div>

<div class="span4">
		<div class="topic_navigation">
		Related:
		
		<br><br>
		<table class="table table-striped">
	  <tbody>
			<% @words.each do |keyword| %>
			<%= link_to keyword[0] + " (" + keyword[1].to_s + ")", :action => "search", :q => keyword[0], :time => params[:time] %> <br><br>
			<%end%>
	  </tbody>

	</table>
	</div>
</div>

app/views/events/show.html.erb
<% provide :title, @event.artist.name + " @ " + @event.venue.name %>
<div class="span8">
	<div id ="event_details">
		<h3><%= link_to @event.artist.name, artist_path(@event.artist) %> @ <%= link_to @event.venue.name, venue_path(@event.venue) %></h3>
		<%= @event.time.strftime("%I:%M %p") %>,
		<%= @event.date.strftime("%a, %b %d") %>
		<br>
		<%= render partial: "venues/venue_address"%>
		<br>
		<% if @event.price? %>
			<%= @event.price %><br>
		<%end%>
		
		<% if @event.user && @event.user.uid != "568790501" %>
		<div class ="author">
			posted by <%= author(@event) %>
		</div>
		<%end%>
		<br>

		<div class = "rsvp">

				RSVP:&nbsp; <%= link_to "Join", :controller => "events", :action => "attend", :event_id => @event.id, :event_url => shoort_url(request.url), :type => "attend" %> · 
		<%= link_to "Maybe", :controller => "events", :action => "attend", :event_id => @event.id, :event_url => shoort_url(request.url), :type => "consider" %>
		</div>
		<div class ="tweetit">
			 <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-text="<%=tweet_text(@event)%>" data-url="<%=shoort_url(request.url)%>" data-counturl="<%=shoort_url(request.url)%>" data-size="small" data-count = "none">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>	
		</div>
		<div class ="fbbuttons">
			<div class="fb-like" data-href="<%= request.url%>" data-send="true" data-layout="button_count" data-width="50" data-show-faces="true"></div>
		</div>
		
				


	</div>

		<div class="fb-comments" data-href="<%= request.url%>" data-num-posts="10" data-width="545"></div>
		<% if current_user && current_user == @event.user %>
			<div class="form-actions">
			  <%= link_to 'Back', events_path, :class => 'btn'  %>
			  <%= link_to 'Edit', edit_event_path(@event), :class => 'btn' %>
			  <%= link_to 'Delete', event_path(@event), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
			</div>
		<%end%>
</div>

<div class="span4">

	<% if @related_events != [] %>
		<div class="related_links">
		Related:
		</div>
		<br>
		<table class="table table-striped">
		  <tbody>
		<%= render @related_events %>
		  </tbody>
		</table>
	<%end%>

	<br>
	<div class="related_links">
		<%= link_to "all events »", root_path %>
	</div>
</div>