config/routes.rb
Stagely::Application.routes.draw do
  resources :artists

  resources :genres
  resources :subgenres

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :venues
  resources :events do
    member do
      get :attend
      get :consider
    end
  end

  match '/search',  to: 'events#search'
  match '/:id' => "shortener/shortened_urls#show"

  match "/auth/:facebook/callback" => "sessions#create"
  match "/auth/failure" => "events#index"

  root :to => 'events#index'

end

app/models/subgenre.rb
class Subgenre < ActiveRecord::Base
	attr_accessible :name, :genre_id
	has_many :events
	has_many :artists
	belongs_to :genre
end

app/controllers/subgenres_controller.rb
class SubgenresController < InheritedResources::Base
	before_filter :power_user, only: [:new, :create, :edit, :update, :destroy]
end

app/views/subgenres/_form.html.erb
<legend><%= controller.action_name.capitalize %> Subgenre</legend>
<%= simple_form_for @subgenre, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>


        <%= f.input :name %>
        <%= f.association :genre %>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', subgenres_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/subgenres/edit.html.erb
<div class="span8">
<%= render :partial => 'form' %>
</div>

app/views/subgenres/index.html.erb
<div class="span8">
<div id ="event_details">
<h3>Subgenres</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
     
    </tr>
  </thead>
  <tbody>
    <% @subgenres.each do |subgenre| %>
      <tr>
        <td><%= link_to subgenre.name, subgenre_path(subgenre) %></td>
        <td>
        <% if current_user && current_user.uid == "568790501" %>
          <%= link_to 'Edit', edit_subgenre_path(subgenre), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', subgenre_path(subgenre), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user && current_user.uid == "568790501" %>
<%= link_to 'New', new_subgenre_path, :class => 'btn btn-primary' %>
<%end%>
</div>

app/views/subgenres/new.html.erb
<div class="span8">
<%= render :partial => 'form' %>
</div>

app/views/subgenres/show.html.erb
<% provide :title, @subgenre.name + " in New York City"%>
<div class="span8">
<div id ="event_details">
<h3><%= (link_to @subgenre.genre.name, genre_path(@subgenre.genre)) %> > <%= @subgenre.name %></h3>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Artists</th>
      <th>Upcoming concerts</th>


    </tr>
  </thead>
  <tbody>
    <% @subgenre.artists.each do |artist| %>
      <tr>
        
        <td><%= link_to artist.name, artist_path(artist) %></td>
        <td><%= artist.events.where("date > ?",Time.now).size %></td>
        <% if current_user && current_user.uid == "568790501" %>
        <td>
          <%= link_to 'Edit', edit_artist_path(artist), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', artist_path(artist), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<% if current_user && current_user.uid == "568790501" %>
<div class="form-actions">
  <%= link_to 'Back', subgenres_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_subgenre_path(@subgenre), :class => 'btn' %>
  <%= link_to 'Delete', subgenre_path(@subgenre), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>
<%end%>
</div>