config/routes.rb
Stagely::Application.routes.draw do
  resources :artists

  resources :genres
  resources :subgenres

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :venues
  resources :events do
    member do
      get :attend
      get :consider
    end
  end

  match '/search',  to: 'events#search'
  match '/:id' => "shortener/shortened_urls#show"

  match "/auth/:facebook/callback" => "sessions#create"
  match "/auth/failure" => "events#index"

  root :to => 'events#index'

end

app/views/layouts/_search.html.erb
	<%= form_tag(:controller => "events", :action => "search", :time => params[:time]) do %>
	  <%= text_field_tag :q, nil, :placeholder => 'Search concerts...'%>
<% end %>







      
 

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="description" content="Concerts in New York City"/>     
    <meta name="keywords" content="Concerts, venues, bands, New York City, stagely"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/eighth-notes.png" />
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30268380-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <header>
  <ul class ="topbar">
    <div class="container">
      <div class="row">

        <li class="offset5 span1">
          <div id ="logo"><%= link_to "stage.ly", root_path%> </div>
        </li>
        
        <li class="offset3 span3">
        <div class ="top-nav">
          
        
<br>
<% if current_user %>
  <%= current_user.name%> | <%= link_to "Sign out", logout_path %>
<% else %>
    <%= link_to 'Sign in with Facebook', "/auth/facebook" %>
<% end %><br>
<h4><%= link_to 'Post a concert', new_event_path%></h4>
</div>
</li>

      </div>
    </div>
    </ul>

        

  </header>

  <body>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=367315919957325";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="row">
        <% if params[:action] != "index" and params[:controller] != "genres" and params[:controller] != "subgenres"%>
          
            <div class="span8">
                    <ul class="breadcrumb" style="list-style-type:none">
                    <li>
                    <a href="/">Home</a>
                    </li>
        
                    <% if @genre_breadcrumb %>
                    <li>
                     > <%= link_to @genre_breadcrumb, :controller => "events", :action => "search", :q => @genre_breadcrumb %>
                    </li>
                    <%end%>
                    <% if @subgenre_breadcrumb %>
                    <li>
                     > <%= link_to @subgenre_breadcrumb, :controller => "events", :action => "search", :q => @subgenre_breadcrumb %>
                    </li>
                    <%end%>



                    <% if @search_breadcrumb %>
                    <li>
                     > "<%= link_to @search_breadcrumb, :controller => "events", :action => "search", :q => @search_breadcrumb %>"
                    </li>
                    <%end%>
                    <% if @action_breadcrumb %>
                    <li>
                     > <%= @action_breadcrumb %>
                    </li>
                    <%end%>
                    </ul>
            </div>
          
            <div class="span1" style="margin-bottom:-18px">
            <%else%>
            <div class="offset8 span1" style="margin-bottom:-18px">
            <%end%>
             <div id ="search"><%= render "layouts/search" %></div>
           </div>
          <%= yield %>
        </div>
      </div>

  </body>
  <div class ="footer">

<br>
  <%= link_to "(c) ", genres_path%> 
  <%= link_to "stage.", artists_path%><%= link_to "ly", venues_path %> 
  </div>
</html>